apiVersion: v1
kind: Service
metadata:
  name: {{ include "tax-app.fullname" . }}-backend-service
  labels:
    {{- include "tax-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "tax-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
  type: ClusterIP