apiVersion: v1
kind: Service
metadata:
  name: {{ include "tax-app.fullname" . }}-postgres-service
  labels:
    {{- include "tax-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "tax-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.servicePort }}
  type: ClusterIP