apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tax-app.fullname" . }}-postgres-pvc
  labels:
    {{- include "tax-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}