# helm/tax-app/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tax-app.fullname" . }}-secrets # Unique name for your secret, tied to the release
  labels:
    {{- include "tax-app.labels" . | nindent 4 }} # Inherits labels from your chart
type: Opaque # Standard type for arbitrary user-defined data

# The 'data' field expects Base64 encoded values.
# Helm's b64enc function handles this encoding for you.
data:
  # jwtSecretKey is read from .Values.secrets.jwtSecretKey at deploy time
  # It will be base64 encoded by Helm.
  jwtSecretKey: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}

  # dbPassword is read from .Values.secrets.dbPassword at deploy time
  # It will be base64 encoded by Helm.
  dbPassword: {{ .Values.secrets.dbPassword | b64enc | quote }}