backend:
  image: dockerhub_username/backend:latest
  containerPort: 5000
  replicas: 2

frontend:
  image: dockerhub_username/frontend:latest
  containerPort: 8000
  replicas: 2

postgres:
  image: postgres:latest
  dbname: taxdb
  user: taxuser
  password: securepassword
  containerPort: 5432
