backend:
  image: mydockd/tax-backend:latest
  containerPort: 5000
  replicas: 1

frontend:
  image: mydockd/tax-frontend:latest
  containerPort: 8000
  replicas: 1

postgres:
  image: postgres:17
  dbname: taxdb
  user: postgres
  password: yourpassword
  db: taxdb
  containerPort: 5432
